/**
 * Title: Pipeline Template Schema
 * Description: Reusable build/run/stop templates
 */

const mongoose = require('mongoose');

const pipelineTemplateSchema = new mongoose.Schema({
    templateName: { type: String, required: true, index: true },
    language: { type: String },
    framework: { type: String },
    buildCommands: { type: [String], default: [] },
    runCommands: { type: [String], default: [] },
    stopCommands: { type: [String], default: [] },
    defaultBranch: { type: String, default: 'main' },
    // Docker support
    useDocker: { type: Boolean, default: false },
    dockerImage: { type: String }, // Base image (e.g., 'node:18-alpine')
    dockerfile: { type: String }, // Path to Dockerfile in repo (e.g., './Dockerfile')
    dockerBuildArgs: { type: [String], default: [] }, // Build arguments (e.g., ['--build-arg', 'NODE_ENV=production'])
    autoGenerateDockerfile: { type: Boolean, default: false }, // Generate Dockerfile if not present
    createdBy: { type: String },
}, { timestamps: true });

module.exports = pipelineTemplateSchema;
