/**
 * Title: Pipeline Template Schema
 * Description: Reusable build/run/stop templates
 */

const mongoose = require('mongoose');

const dockerBuildArgSchema = new mongoose.Schema({
    key: { type: String, required: true },
    value: { type: String, default: '' },
}, { _id: false });

const pipelineTemplateSchema = new mongoose.Schema({
    templateName: { type: String, required: true, index: true },
    language: { type: String },
    framework: { type: String },
    buildCommands: { type: [String], default: [] },
    runCommands: { type: [String], default: [] },
    stopCommands: { type: [String], default: [] },
    defaultBranch: { type: String, default: 'main' },
    // Docker support
    useDocker: { type: Boolean, default: false },
    dockerImage: { type: String }, // Base image (e.g., 'node:18-alpine')
    dockerfile: { type: String }, // Path to Dockerfile in repo (e.g., './Dockerfile')
    dockerBuildArgs: { type: [dockerBuildArgSchema], default: [] }, // Build arguments as key-value pairs
    autoGenerateDockerfile: { type: Boolean, default: false }, // Generate Dockerfile if not present
    createdBy: { type: String },
}, { timestamps: true });

module.exports = pipelineTemplateSchema;
